# Generated by Django 5.2 on 2025-04-29 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('duration_years', models.PositiveIntegerField()),
                ('total_credits', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.program')),
            ],
            options={
                'ordering': ['program', 'semester_number'],
                'unique_together': {('program', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('credits', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.semester')),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
    ]
