# Generated by Django 5.2.5 on 2025-09-02 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('semester', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective')], default='CORE', max_length=20)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.batch')),
                ('faculty', models.ForeignKey(blank=True, limit_choices_to={'role': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.program')),
            ],
        ),
    ]
