# Generated by Django 5.2 on 2025-04-29 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('matric_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intermediate_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quota', models.CharField(blank=True, max_length=50)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.program')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_application', to='students.student')),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
    ]
