# Generated by Django 5.2.5 on 2025-09-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_faculty', models.PositiveIntegerField(default=0)),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('fees_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attendance_avg_percent', models.FloatField(default=0.0)),
                ('avg_gpa', models.FloatField(default=0.0)),
                ('hostel_occupancy_percent', models.FloatField(default=0.0)),
                ('cafeteria_active_subscriptions', models.PositiveIntegerField(default=0)),
                ('transport_active_passes', models.PositiveIntegerField(default=0)),
                ('sports_active_memberships', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
