name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13.7]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: django_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U django"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django Tests
      env:
        POSTGRES_DB: django_test
        POSTGRES_USER: django
        POSTGRES_PASSWORD: django
        POSTGRES_HOST: postgres   # matches the service name
        POSTGRES_PORT: 5432
        DJANGO_SETTINGS_MODULE: ums.settings  # ⬅️ change to your project name
        SECRET_KEY: dummysecretkey
        DEBUG: "1"
      run: |
        cd Campus-Management-System-with-Chatbot-support/ums/
        python manage.py migrate --noinput
        python manage.py test
